replicaCount: 1

image:
  repository: my-app-image
  pullPolicy: Never
  command:
    - sh
    - -c
  args:
    - "npm install && npm run dev"

namespace: my-namespace
appName: my-app

volume:
  hostPath: /mnt/demo
  mountPath: /usr/src/app
  type: Directory

service:
  type: NodePort
  port: 80
  targetPort: 5173
  nodePort: 30000

serviceAccount:
  create: true
  name: ""  # Set a custom service account name or leave it empty for automatic naming

ingress:
  enabled: true
  className: nginx  # Use the ingress class name (e.g., nginx, traefik, etc.)
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "example.local"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "example.local"
      secretName: example-tls-secret

autoscaling:
  enabled: false           # Set true to enable autoscaling
  minReplicas: 1           # Minimum number of replicas
  maxReplicas: 10          # Maximum number of replicas
  targetCPUUtilizationPercentage: 80  # Target CPU utilization (optional)
  targetMemoryUtilizationPercentage: 80  # Target memory utilization (optional)
